#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

sudo apt-get update -y

sudo apt-get install haproxy -y 

# edit config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 377934-web-01 52.91.149.193:80 check
        server 377934-web-02 52.91.119.58:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
